---
# tasks file for vultr

- name: create server
  local_action:
    module: vultr_server
#    name: "{{ vultr_server_name }}"
    name: "{{ inventory_hostname_short }}"
    os: Ubuntu 18.04 x64
    plan: 1024 MB RAM,25 GB SSD,1.00 TB BW
    region: Chicago
    state: present
  tags: [create_server, never]

#- name: save server information of created server to file for future reference 
#  local_action:
#    module: copy 
#    content: "{{ vultr_server_name }}_response"
#    dest: "../files/{{ vultr_server_name }}_server.yml"
#    tags: create_server

- name: destroy server
  local_action:
    module: vultr_server
#    name: "{{ vultr_server_name }}"
    name: "{{ inventory_hostname_short }}"
    state: absent
  tags: [destroy_server, never]

#- name: remove server information file of destroyed server since it will no longer be needed
#  local_action:
#    module: file
#    path: "../files/{{ vultr_server_name }}_server.yml"
#    state: absent
#    tags: destroy_server

- name: ensure a server is present and started
  local_action:
    module: vultr_server
#    name: "{{ vultr_server_name }}"
    name: "{{ inventory_hostname_short }}"
    state: started
