---
# tasks file for vultr

- name: create server
  local_action:
    module: vultr_server
    name: "{{ inventory_hostname_short }}"
    api_key: "{{ vultr_api_key }}"
    os: Ubuntu 18.04 x64
    plan: 1024 MB RAM,25 GB SSD,1.00 TB BW
    region: Chicago
    state: present
  tags: [create_server, never]

- name: destroy server
  local_action:
    module: vultr_server
    name: "{{ inventory_hostname_short }}"
    api_key: "{{ vultr_api_key }}"
    state: absent
  tags: [destroy_server, never]

- name: ensure a server is present and started
  local_action:
    module: vultr_server
    name: "{{ inventory_hostname_short }}"
    api_key: "{{ vultr_api_key }}"
    state: started
