---
# tasks file for php

- name: install php 8.1 repository from ppa:ondrej/php
  apt_repository:
     repo: "ppa:ondrej/php"

- name: Install PHP and its modules
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - php8.1
      - php8.1-cli
      - php8.1-curl
      - php8.1-gd
      - php-imagick
      - php8.1-json
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-pdo
      - php8.1-xml
      - php8.1-xmlrpc
      - php-xdebug
      - php8.1-zip
