---
# tasks file for php

- name: install php 7.2 repository from ppa:ondrej/php
  apt_repository:
     repo: "ppa:ondrej/php"

- name: Install PHP and its modules
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - php7.2
      - php7.2-cli
      - php7.2-curl
      - php7.2-gd
      - php-imagick
      - php7.2-json
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-pdo
      - php7.2-xml
      - php7.2-xmlrpc
      - php-xdebug
      - php7.2-zip
