---
# tasks file for php

- name: install php 7.4 repository from ppa:ondrej/php
  apt_repository:
     repo: "ppa:ondrej/php"

- name: Install PHP and its modules
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - php7.4
      - php7.4-cli
      - php7.4-curl
      - php7.4-gd
      - php-imagick
      - php7.4-json
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-pdo
      - php7.4-xml
      - php7.4-xmlrpc
      - php-xdebug
      - php7.4-zip
